# Generated by Django 3.1.2 on 2020-10-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuser', '0002_auto_20201029_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='izuser',
            options={'verbose_name_plural': '아이즈원 사용자'},
        ),
        migrations.AddField(
            model_name='izuser',
            name='useremail',
            field=models.CharField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
